run-name: call_workflow_template

on:
  workflow_dispatch:
    branches:
      - "workflow-template-implementation"
    inputs:
      environment:
        type: choice
        description: 'Version Tag to Release'
        default: 'dev'
        required: true
        options:
        - dev
        - prod

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/run_chain_template.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit # pass all secrets