name: dbt_run_adhoc_dev
run-name: dbt_run_adhoc_dev

on:
  workflow_dispatch:
    branches:
      - main
      - update-profiles-env-settings
    inputs:
      environment:
        type: string
        description: 'Environment to run the DBT command'
        required: true
        default: 'prod' 
        type: choice
        options:
        - dev
        - prod
        - workflow
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true

env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE: "${{ secrets.DATABASE }}"
  WAREHOUSE: "${{ secrets.WAREHOUSE }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    strategy:
      matrix:
        command: ${{fromJson(inputs.dbt_command)}}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          ${{ matrix.command }}