name: adhoc_dbt_run
run-name: call_workflow_template

on:
  workflow_dispatch:
    branches:
      - main
      - test_update_dbt_adhoc_command
    inputs:
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE_DEV: "${{ secrets.DATABASE_DEV }}"
  DATABASE_PROD: "${{ secrets.DATABASE_PROD }}"
  WAREHOUSE_DEV: "${{ secrets.WAREHOUSE_DEV }}"
  WAREHOUSE_PROD: "${{ secrets.WAREHOUSE_PROD }}"
  SCHEMA: "${{ secrets.SCHEMA }}"


jobs:
  install_dependencies:
    uses: FlipsideCrypto/analytics-workflow-templates/.github/workflows/install_dependencies.yml@main
    secrets: inherit 

  run_dbt_jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        msg: ${{fromJson(inputs.dbt_command)}}
    steps:
      - name: Send greeting
        run: echo "Hello ${{ matrix.msg }}"
  