name: dbt_run

on:
  push:
    branches:
      - "main"
      - "slack-alerts"
  # uncheck the following to set it up with CRON
  # schedule:
  # Runs "every 10 mins"
  # - cron: "*/10 * * * *"

env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ secrets.ACCOUNT }}"
  ROLE: "${{ secrets.ROLE }}"
  USER: "${{ secrets.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ secrets.REGION }}"
  DATABASE_DEV: "${{ secrets.DATABASE_DEV }}"
  DATABASE_PROD: "${{ secrets.DATABASE_PROD }}"
  WAREHOUSE_DEV: "${{ secrets.WAREHOUSE_DEV }}"
  WAREHOUSE_PROD: "${{ secrets.WAREHOUSE_PROD }}"
  SCHEMA: "${{ secrets.SCHEMA }}"

jobs:
  scheduled_run:
    name: dbt_run
    runs-on: ubuntu-latest
    environment:
      name: workflow

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip install dbt-snowflake cli-passthrough
          dbt deps

      - name: Run dbt models
        run: |
          python alert.py dbt run -m ./models/streamline/streamline__blocks_history.sql
          python alert.py dbt test -m ./models/streamline/streamline__blocks_history.sql

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
            name: failed-tests-artifact
            path: ./target/run/run_results.json