version: 2

sources:
  - name: bronze
    database: streamline
    schema: |
      {{ "AXELAR_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AXELAR" }}
    tables:
      - name: blocks_v2
      - name: blocks
      - name: tx_counts_v2
      - name: tx_counts
      - name: txs_v2
      - name: txs
      - name: txs_details
      - name: validators
      - name: blocks_test_queue
      - name: axelscan_day_counts_gmp
      - name: axelscan_day_counts_transfers
      - name: axelscan_searchgmp
      - name: axelscan_searchtransfers
  - name: tokens
    database: osmosis
    schema: core
    tables: 
      - name: dim_labels
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'AXELAR' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_dates
      - name: dim_date_hours
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'AXELAR' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: number_sequence
      - name: labels_combined
      - name: hourly_prices_coin_gecko
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      - name: logs
      - name: transfers
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      # - name: logs
      - name: transfers
  - name: bsc_silver
    database: bsc
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      - name: logs
      - name: transfers
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      - name: logs
      - name: transfers
  - name: polygon_silver
    database: polygon
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      # - name: logs
      - name: transfers
  - name: optimism_silver
    database: optimism
    schema: silver
    tables: 
      - name: decoded_logs
      - name: logs
      - name: contracts
  - name: base_silver
    database: base
    schema: silver
    tables: 
      - name: decoded_logs
      - name: logs
      - name: contracts
  - name: arbitrum
    database: arbitrum
    schema: core
    tables: 
      - name: dim_contracts
  - name: avalanche
    database: avalanche
    schema: core
    tables: 
      - name: dim_contracts
  - name: ethereum
    database: ethereum
    schema: core
    tables: 
      - name: dim_contracts
  - name: polygon
    database: polygon
    schema: core
    tables: 
      - name: dim_contracts
  - name: bsc
    database: bsc
    schema: core
    tables: 
      - name: dim_contracts
  - name: optimism
    database: optimism
    schema: core
    tables: 
      - name: dim_contracts
  - name: base
    database: base
    schema: core
    tables: 
      - name: dim_contracts
  - name: github_actions
    database: axelar
    schema: github_actions
    tables:
      - name: workflows
  - name: bronze_api
    database: axelar
    schema: bronze_api
    tables:
      - name: axelscan_searchgmp