version: 2

sources:
  - name: bronze
    database: streamline
    schema: |
      {{ "AXELAR_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AXELAR" }}
    tables:
      - name: blocks
      - name: txs
      - name: txs_details
      - name: validators
  - name: tokens
    database: osmosis
    schema: core
    tables: 
      - name: dim_labels
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "AXELAR_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AXELAR" }}
    tables:
      - name: blocks
      - name: txs
      - name: txs_details
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
