version: 2

sources:
  - name: bronze
    database: streamline
    schema: |
      {{ "AXELAR_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AXELAR" }}
    tables:
      - name: blocks
      - name: txs
      - name: txs_details
      - name: validators
  - name: tokens
    database: osmosis
    schema: core
    tables: 
      - name: dim_labels
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'AXELAR' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: address_labels
      - name: dim_dates
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "AXELAR_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AXELAR" }}
    tables:
      - name: blocks
      - name: txs
      - name: txs_details
  - name: osmo
    database: osmosis
    schema: silver
    tables: 
      - name: asset_metadata
  - name: arbitrum_silver
    database: arbitrum
    schema: silver
    tables: 
      - name: contracts
      - name: logs
      - name: transfers
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      - name: logs
      - name: transfers
  - name: bsc_silver
    database: bsc
    schema: silver
    tables: 
      - name: logs
      - name: transfers
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      - name: logs
      - name: transfers
  - name: polygon_silver
    database: polygon
    schema: silver
    tables: 
      - name: contracts
      - name: decoded_logs
      - name: logs
      - name: transfers
  - name: arbitrum
    database: arbitrum
    schema: core
    tables: 
      - name: dim_contracts
  - name: avalanche
    database: avalanche
    schema: core
    tables: 
      - name: dim_contracts
  - name: ethereum
    database: ethereum
    schema: core
    tables: 
      - name: dim_contracts
  - name: polygon
    database: polygon
    schema: core
    tables: 
      - name: dim_contracts